Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [2]:
import numpy as np
import pandas as pd
from scipy import stats
from matplotlib import pyplot as plt

KeyboardInterrupt: 

In [3]:
salary = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110] 
scoring = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

Рассчитаем ковариацию по формуле 
COV = M[(X-M(X))(Y-M(Y))] = M(XY) - M(X)M(Y) = X_Y_ - X_*Y_

In [4]:
XY=0
X=0
Y=0
n = len(salary)
for i in range(0,n):
    XY = XY+salary[i]*scoring[i]
    X = X+salary[i]
    Y = Y+scoring[i]
X_avg = X/n
Y_avg = Y/n
cov = XY/n - X_avg*Y_avg

print(f'Ковариация смещенная:{cov}')
np.cov(salary,scoring,ddof=0)

Ковариация смещенная:9157.839999999997


array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

Высчитаем несмещённую оценку 

In [6]:
sum_1 = 0
for i in range(0,n):
   sum_1 = sum_1 + (salary[i]-X_avg)*(scoring[i]-Y_avg)
cov_1 = 1/(n-1)*sum_1

print(f'Несмещенная ковариация:{cov_1}')
np.cov(salary,scoring,ddof=1)

Несмещенная ковариация:10175.377777777776


array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [7]:

sum_X = 0
sum_Y = 0
for i in range(0,n):
    sum_X = sum_X + (salary[i]-X_avg)**2
    sum_Y = sum_Y + (scoring[i]-Y_avg)**2
Dx = 1/(n)*sum_X
Dy = 1/(n)*sum_Y
scale_X = Dx**0.5
scale_Y = Dy**0.5
print(Dx, scale_X)
print(Dy, scale_Y)

3494.6400000000003 59.115480206118605
30468.89000000001 174.55340157098058


In [9]:
r = cov/(scale_X*scale_Y)
print('r =',r)
print('Решение через Numpy:')
np.corrcoef(salary, scoring)


r = 0.8874900920739158
Решение через Numpy:


array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

print('Проверка через Pandas:')
pd.DataFrame({'x': salary, 'y': scoring}).corr(method='kendall')